"""create draws and draw_numbers

Revision ID: 9af877f7b422
Revises: 
Create Date: 2026-08-12 02:44:04.259140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af877f7b422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draws',
    sa.Column('lottery_type', sa.SmallInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lottery_type', 'period_id')
    )
    op.create_table('draw_numbers',
    sa.Column('lottery_type', sa.SmallInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('ball', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('ball >= 1 AND ball <= 49', name='ck_draw_numbers_ball_range'),
    sa.CheckConstraint('position >= 1 AND position <= 7', name='ck_draw_numbers_position_range'),
    sa.ForeignKeyConstraint(['lottery_type', 'period_id'], ['draws.lottery_type', 'draws.period_id'], ),
    sa.PrimaryKeyConstraint('lottery_type', 'period_id', 'position'),
    sa.UniqueConstraint('lottery_type', 'period_id', 'ball', name='uq_draw_numbers_period_ball')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draw_numbers')
    op.drop_table('draws')
    # ### end Alembic commands ###
